import type { CatalogProduct } from './catalog.types'

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    brand: 'Apple',
    monthlyPrice: 33.3,
    originalPrice: 999,
    rating: 4.9,
    reviewCount: 124,
    storageOptions: ['128 GB', '256 GB', '512 GB', '1 TB'],
    colorOptions: ['Graphite', 'Titanium', 'Ocean'],
    availability: 'in-stock',
    description: 'Titanium performance phone with premium camera system and same-day activation.',
    badge: 'Trade-in value up to $650',
    heroGradient: 'linear-gradient(135deg, #f3f4f8 0%, #bbc6d6 100%)',
    supportNote: 'Get it by Friday with express delivery',
  },
  {
    id: 'samsung-galaxy-s24',
    name: 'Samsung Galaxy S24',
    brand: 'Samsung',
    monthlyPrice: 27.8,
    originalPrice: 839,
    rating: 4.8,
    reviewCount: 86,
    storageOptions: ['128 GB', '256 GB', '512 GB'],
    colorOptions: ['Lilac', 'Graphite', 'Ocean'],
    availability: 'in-stock',
    description: 'AI-assisted flagship with vivid display, advanced zoom, and instant plan setup.',
    badge: 'Bundle and save on accessories',
    heroGradient: 'linear-gradient(135deg, #ded7ff 0%, #8c7de4 100%)',
    supportNote: 'Popular with upgrade-ready accounts',
  },
  {
    id: 'google-pixel-8',
    name: 'Google Pixel 8',
    brand: 'Google',
    monthlyPrice: 19.4,
    originalPrice: 699,
    rating: 4.7,
    reviewCount: 51,
    storageOptions: ['128 GB', '256 GB'],
    colorOptions: ['Hazel', 'Ocean', 'Graphite'],
    availability: 'low-stock',
    description: 'Clean Android experience with fast camera tools and premium call intelligence.',
    badge: 'Low-stock on Hazel finish',
    heroGradient: 'linear-gradient(135deg, #d6f3ed 0%, #56b7a8 100%)',
    supportNote: 'Reserve in cart for 15 minutes once selected',
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    brand: 'Apple',
    monthlyPrice: 26.7,
    originalPrice: 799,
    rating: 4.6,
    reviewCount: 72,
    storageOptions: ['128 GB', '256 GB', '512 GB'],
    colorOptions: ['Ocean', 'Graphite', 'Titanium'],
    availability: 'preorder',
    description: 'Balanced premium device for assisted and self-service transactions.',
    badge: 'Pre-order bonus includes setup support',
    heroGradient: 'linear-gradient(135deg, #f9e5dd 0%, #e19378 100%)',
    supportNote: 'Ships next week for pre-order customers',
  },
  {
    id: 'samsung-galaxy-z-flip',
    name: 'Samsung Galaxy Z Flip',
    brand: 'Samsung',
    monthlyPrice: 31.5,
    originalPrice: 949,
    rating: 4.4,
    reviewCount: 40,
    storageOptions: ['256 GB', '512 GB'],
    colorOptions: ['Lilac', 'Graphite'],
    availability: 'out-of-stock',
    description: 'Foldable premium phone for fashion-forward upgrades and bundled plans.',
    badge: 'Notify me when inventory returns',
    heroGradient: 'linear-gradient(135deg, #f2d9ff 0%, #b477df 100%)',
    supportNote: 'Currently unavailable for direct purchase',
  },
  {
    id: 'google-pixel-fold',
    name: 'Google Pixel Fold',
    brand: 'Google',
    monthlyPrice: 44.4,
    originalPrice: 1499,
    rating: 4.5,
    reviewCount: 28,
    storageOptions: ['256 GB', '512 GB'],
    colorOptions: ['Hazel', 'Graphite'],
    availability: 'in-stock',
    description: 'Large-screen premium foldable built for multitasking and assisted sales bundles.',
    badge: 'Includes premium care option',
    heroGradient: 'linear-gradient(135deg, #dde7f9 0%, #7f9ad1 100%)',
    supportNote: 'Available for premium financing plans',
  },
]
